services:
  - type: web
    name: fractured-arcanum
    env: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_ORIGIN
        value: https://farcanum.anomalousinteractive.com
      - key: PUBLIC_APP_URL
        value: https://farcanum.anomalousinteractive.com
      - key: WEBAUTHN_ORIGIN
        value: https://farcanum.anomalousinteractive.com
      - key: WEBAUTHN_RP_ID
        value: farcanum.anomalousinteractive.com
      - key: WEBAUTHN_RP_NAME
        value: Fractured Arcanum
